create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  order_text text not null,
  po_number text,
  requested_ship_date date not null,
  lot_numbers text,
  ready_to_ship boolean not null default false,
  delivered boolean not null default false,
  created_by uuid references auth.users(id),
  created_by_email text,
  updated_by uuid references auth.users(id),
  updated_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;

drop policy if exists "Authenticated users can read orders" on public.orders;
create policy "Authenticated users can read orders" on public.orders
for select to authenticated using (true);

drop policy if exists "Authenticated users can add orders" on public.orders;
create policy "Authenticated users can add orders" on public.orders
for insert to authenticated with check (auth.uid() = created_by);

drop policy if exists "Authenticated users can update orders" on public.orders;
create policy "Authenticated users can update orders" on public.orders
for update to authenticated using (true) with check (auth.uid() = updated_by);

drop policy if exists "Authenticated users can delete orders" on public.orders;
create policy "Authenticated users can delete orders" on public.orders
for delete to authenticated using (true);

create index if not exists idx_orders_ship_date on public.orders (delivered, requested_ship_date);
